# You can find the default config with description of parameters here:
# https://github.com/arboriginal/SCT-CoordsTracker/blob/master/src/settings.yml
#
# Permissions for this tracker are listed here:
# https://github.com/arboriginal/SCT-CoordsTracker/blob/master/README.md#permissions

settings:
  check_update: true # If true, when you (re)load the plugin, it try to check if a new version is available
  autoload_target: false # If true, permissions "scompass.track.auto.COORDS.<name>" are activated
  inactive_target: false # If true, inactive targets will be added to compasses too (can affect performances and disturb display)

  symbol: "§e☉" # Symbol displayed on the compass to represent this kind of trackers positions.
  temp:   "ϼ"   # Advanced: Symbol temporary used by the plugin, must be unique, 1 char and not used in "symbol".

  auto_activated: true # If true, the tracker is automatically activated when a position is created
  auto_disabled: 5 # If player closer than this (in blocks) from the target, the tracking stop automatically (0 to disable). 

  limits:
    ADD: 10  # Number of maximum named coords a player can define
    START: 1 # Number of maximum simultaneous positions a player (from this tracker) can track

  # Require settings.inactive_target:true
  inactive_symbol: "§7☉" # Symbol displayed on the compass to represent inactive targets of this kind of trackers positions.
  inactive_temp:   "☰"   # Advanced: Symbol temporary used by the plugin, must be unique, 1 char and not used in "symbol" nor "inactive_symbol".

  # Those parameters are used to highlight active targets when you facing them
  hl_angle: 0      # Angle in degree (integer) centered on compass middle point to be considered as faced (for example 30 means from 60° to 120°)
  hl_symbol: "§b☉" # Symbol displayed on the compass to represent active targets you are facing (require hl_angle > 0)
  hl_temp: "♳"     # Advanced: Symbol temporary used by the plugin (only used when hl_angle > 0)

locales:
  en:
    name: "coords" # Only use alphabetic and numeric values, not space

    list: "{prefix}&rNamed coordinates: {list}."
    list_empty: "{prefix}&rNo named coordinates."

    ADD: "{prefix}&aNamed coordinate &e{target}&a has been created."
    DEL: "{prefix}&aNamed coordinate &e{target}&a has been deleted."
    START: "{prefix}&6You are now tracking &e{target}&6 coordinate."
    STOP: "{prefix}&6You no longer track &e{target}&6 coordinate."

    help:
      noargs: |
        &r- &c/{command} &e{tracker}
        &7  Show the list of your named coordinates.
      ADD: |
        &r- &c/{command} &e{tracker} &6{ADD} &3<name> &b<x> <z>
        &7  Add a new named coordinate.
      DEL: |
        &r- &c/{command} &e{tracker} &6{DEL} &3<name>
        &7  Delete a named coordinate.
      START: |
        &r- &c/{command} &e{tracker} &6{START} &3<name>
        &7  Begin the tracking of this named coordinate.
      STOP: |
        &r- &c/{command} &e{tracker} &6{STOP} &3<name>
        &7  End the tracking of this named coordinate.

    target_auto_disabled: "{prefix}&3You've reached &b{target}&3, tracking disabled in &b{tracker}&3 tracker."

  fr:
    name: "coords" # N'utilise que des chiffres et des lettres, pas d'espace

    list: "{prefix}&rCoordonnées nommées : {list}."
    list_empty: "{prefix}&rAucunes coordonnées nommées."

    ADD: "{prefix}&aLes coordonnées &e{target}&a ont été créées."
    DEL: "{prefix}&aLes coordonnées &e{target}&a ont été supprimée."
    START: "{prefix}&6Tu pistes maintenant les coordonnées &e{target}&6."
    STOP: "{prefix}&6Tu ne pistes plus les coordonnées &e{target}&6."

    help:
      noargs: |
        &r- &c/{command} &e{tracker}
        &7  Affiche la liste des coordonnées nommées.
      ADD: |
        &r- &c/{command} &e{tracker} &6{ADD} &3<nom> &b<x> <z>
        &7  Crée une coordonnée nommée.
      DEL: |
        &r- &c/{command} &e{tracker} &6{DEL} &3<nom>
        &7  Supprime une coordonnée nommée.
      START: |
        &r- &c/{command} &e{tracker} &6{START} &3<nom>
        &7  Démarre le pistage d'une coordonnée nommée.
      STOP: |
        &r- &c/{command} &e{tracker} &6{STOP} &3<nom>
        &7  Arrête le pistage d'une coordonnée nommée.

    target_auto_disabled: "{prefix}&3Tu as atteint &b{target}&3, pistage désactivé dans le tracker &b{tracker}&3."
